/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Context"): TruffleContracts.ContextContract;
      require(
        name: "DoubleLinkedList"
      ): TruffleContracts.DoubleLinkedListContract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "Issuance"): TruffleContracts.IssuanceContract;
      require(name: "IssuanceToken"): TruffleContracts.IssuanceTokenContract;
      require(name: "LinkedList"): TruffleContracts.LinkedListContract;
      require(
        name: "LinkedListAsArray"
      ): TruffleContracts.LinkedListAsArrayContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(name: "RBAC"): TruffleContracts.RBACContract;
      require(name: "RBACExtended"): TruffleContracts.RBACExtendedContract;
      require(name: "StateMachine"): TruffleContracts.StateMachineContract;
      require(
        name: "StringConversion"
      ): TruffleContracts.StringConversionContract;
      require(
        name: "TestStateMachine"
      ): TruffleContracts.TestStateMachineContract;
    }
  }
}
